package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            githubConnection {
                id = "PROJECT_EXT_4"
                displayName = "GitHub.com"
                clientId = "Ov23liQIXdwNgaXrA9IJ"
                clientSecret = "credentialsJSON:5e0075d4-fbfe-4871-86dd-91cd92ae265a"
            }
        }
    }
}
