package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'HttpsGithubComPiotrnajberekAnsibleRefsHeadsMain'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("HttpsGithubComPiotrnajberekAnsibleRefsHeadsMain")) {
    val expected = GitVcsRoot({
        id("HttpsGithubComPiotrnajberekAnsibleRefsHeadsMain")
        name = "https://github.com/piotrnajberek/ansible#refs/heads/main"
        url = "https://github.com/piotrnajberek/ansible"
        branch = "refs/heads/main"
        authMethod = password {
            userName = "piotrnajberek"
            password = "credentialsJSON:c29674f8-a043-48e9-93cd-526307de67ae"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "piotrnajberek"
            password = "credentialsJSON:1a13fa64-4a8a-43c6-9b39-f73c2eccb5dd"
        }
    }

}
